version: "3.3"

services:
  bookstore:
    image: bookstore
    ports:
      - "80:80"
    depends_on:
      - database
  database:
    image: mysql:8.0.28-debian
    ports:
      - "3306:3306"
    hostname: database
    volumes:
      - ./config/initialize_db.sql:/docker-entrypoint-initdb.d/initialize_db.sql
      - ~/Documents/data/mysql/bookstore:/var/lib/mysql
    env_file:
      - database.env
